### ISSUE TITLE
New Color Part 3

### ISSUE THREAD

**Issue by PlavnikHacks** [HackerHansen/1v1.lol-aimbot#14]
Okay thank you I guess, maybe say the cheat is discontinued instead of lying people?

**Comment by HackerHansen** [comment]
... 

Just because I'm not helping you doesnt mean I'm lying. Idk how you pulled that from the other issues you created. 

If you check my yt comments for this video, a lot of people are saying that the aimbot just looks at the sky and spins. If you ever considered to scroll down you could see where I'm getting my words from. I think that's pretty solid proof. You don't need to be salty when you don't get help from a 15 year old lmao
